language: python
python: 3.6
branches: master
install:
- pip install mkdocs mkdocs-material pymdown-extensions pygments
script: true
before_deploy:
- mkdocs build --verbose --clean --strict
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: site
  on:
    branch: master
env:
  matrix:
    secure: j6f8fMqh/uuOWAn0nRx81m2Ne3xO1JQF05773AZgzWdb0frYx2iEQVQ1g4JvSOhqPt5zX7FWtfJNSkVMgRlqUYoFKy7Tretllq1MmOTjYPE5GkgxEwG15Q2PIHH2Wr5pYC2iH82C/zyCk8H9LXvcjhFUvCAeQC2PYOaM7iv6WRF1lPQxW8LH7dI8dMRrKpmMaf/hGN59TIcarnFaeX37nHt6DFowZhCors8kg1pN2+dUnlEsVjvcFTGzEnwa2HpVlSPD77hQGuh+KTn9iYw95qpxOzKKIqw5QcH98KiVTYAwkC5fKMUVhlRyIPJuXU4BF2k6sjlEf7yFvvJlspFqVOjUdmB0cV06i/NWJo1jDvXL4xiWJLwsgxkPXvrMmJbhvftUXo4M1hatwnUABfSe2dvXEzawYJZ0sx+Bn/4UOpL1jYcWDNAwHpG0MVcD4DlcgzH4LbeOJ9uPDNDDQoGWbZQMKkvNYvrPppFQdrqLWnicjpnhLJxuF/deR2mzukJSs8CEwtNKOvyew259OZhp539fJctU+F1CQOP8r5sY6FPYpFh0cUsvA67TSDvka67rvQM6R1h9M4WoC2RED3aatu0NSe+1ZngffmLC3xzuHYrJXxk583RnDNhYjT75qs+JszvwehdG43q2ckHu+POP16of54mmA2U38rHuVDoAe+U=
