site_name: Requisitos de Software - Shazam
repo_name: 'Requisitos2-2019/Shazam'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Shazam'
site_description: 'Requisitos de Software do aplicativo Shazam'

nav:
  - Home: 'index.md'
  - Pré-Rastreabilidade:
    - Rich Pictures: 'pre-rastreabilidade/rich-pictures/index.md'
  - Elicitação:
    - Introspecção: 'elicitacao/introspeccao.md'
    - Análise de Protocolo: 'elicitacao/analise_protocolo.md'
    - Questionário:
      - V0.0: 'elicitacao/questionario/questionario_v0.md'
      - V0.1: 'elicitacao/questionario/questionario_v1.md'
      - Resultados: 'elicitacao/questionario/resultados.md'
    - Observação: 'elicitacao/observacao.md'
    - Brainstorming: 'elicitacao/brainstorming.md'
    - Priorização: 'priorizacao/firstThingFirst.md'
  - Modelagem:
    - Cenários: 'modelagem/cenarios.md'
    - Léxicos: 'modelagem/lexicos.md'
    - Diagramas de Casos de Uso: 'modelagem/diagramas.md'
    - Especificações de casos de uso: 'modelagem/especificacao_dcu.md'
    - Especificação Suplementar: 'modelagem/especificacaoSuplementar.md'
    - Backlog do Produto: 'modelagem/backlog.md'
    - NFR: 'modelagem/NFR.md'
  - Análise: 
    - NFR: 'analise/NFR.md'
    - Casos de Uso: 'analise/diagramas_casos_uso.md'
    - Rich Pictures: 'analise/rich_pictures.md'
    - Observação: 'analise/observacao.md'
    - Léxicos: 'analise/lexicos.md'
    - Brainstorming: 'analise/brainstorming.md'
    - Validação: 'analise/email_suporte.md'  
    - Backlog: 'analise/backlog.md'
    - Análise de Protocolo: 'analise/analise_de_protocolo.md'
    - Cenários: 'analise/cenarios.md'
    - Especificação Suplementar: 'analise/especificacao_suplementar.md'
    - Introspecção: 'analise/introspeccao.md'
    - Questionário: 'analise/questionarios.md'
  - Pós-Rastreabilidade:
    - Backward-From: 'pos-rastreabilidade/backwardFrom.md'
    - Forward-From: 'pos-rastreabilidade/forwardFrom.md'

theme:
  name: 'material'
  palette:
    accent: 'indigo'
    # primary: '#08f'
  logo: 'assets/img/shazam-logo.png'
  favicon: 'assets/img/favicon.ico'
  language: 'pt'


extra_css:
    - css/extra.css
